name: CI/CD Pipeline (macOS)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 3: Run Cypress tests and generate report
      - name: Run Cypress tests and generate report
        run: |
          npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/results
        env:
          CI: true

      # Step 4: Upload Cypress test results as artifact (optional)
      - name: Upload Cypress test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results/

      # Step 5: Check if report exists
      - name: Check if report exists
        run: |
          ls -l cypress/results/
          cat cypress/results/final-report.html

      # Step 6: Send email with Cypress HTML report and assets
      - name: Send email with Cypress report and assets
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: yurkasedow0@gmail.com  # Ваш email
          from: ${{ secrets.MAIL_USERNAME }}  # Используем MAIL_USERNAME для отправителя
          subject: 'Cypress Test Report'
          body: |
            <html>
              <body>
                <h2>Cypress Test Report</h2>
                <p>The test results are attached in the report.</p>
              </body>
            </html>
          attachments: |
            cypress/results/final-report.html  # HTML отчет
            ${{ steps.files.outputs.files }}
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

      - name: Get list of all files in assets directory
        id: files
        run: |
          files=$(find cypress/results/assets -type f)
          echo "files=$files" >> $GITHUB_ENV